using AutoMapper;
using FSCMS.Core.Entities;
using FSCMS.Service.ReponseModel;
using FSCMS.Service.RequestModel;
using System;

namespace FSCMS.Service.Mapping
{
    public class DocumentTemplateMappingProfile : Profile
    {
        public DocumentTemplateMappingProfile()
        {
            // Map entity -> basic response
            CreateMap<DocumentTemplate, DocumentTemplateResponse>()
                .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
                .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name))
                .ForMember(dest => dest.Code, opt => opt.MapFrom(src => src.Code))
                .ForMember(dest => dest.Content, opt => opt.MapFrom(src => src.Content))
                .ForMember(dest => dest.TemplateType, opt => opt.MapFrom(src => src.TemplateType))
                .ForMember(dest => dest.Version, opt => opt.MapFrom(src => src.Version))
                .ForMember(dest => dest.IsActive, opt => opt.MapFrom(src => src.IsActive))
                .ForMember(dest => dest.CreatedBy, opt => opt.MapFrom(src => src.CreatedBy))
                .ForMember(dest => dest.UpdatedBy, opt => opt.MapFrom(src => src.UpdatedBy))
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.CreatedAt))
                .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(src => src.UpdatedAt));

            // Map entity -> detail response (include base mapping)
            CreateMap<DocumentTemplate, DocumentTemplateDetailResponse>()
                .IncludeBase<DocumentTemplate, DocumentTemplateResponse>()
                .ForMember(dest => dest.TotalVersion, opt => opt.Ignore()) // can calculate in service
                .ForMember(dest => dest.CreatedByName, opt => opt.Ignore()) // optional: map from User table if needed
                .ForMember(dest => dest.UpdatedByName, opt => opt.Ignore());

            // Map create request -> entity
            CreateMap<CreateDocumentTemplateRequest, DocumentTemplate>()
                .ForMember(dest => dest.Id, opt => opt.Ignore()) // generated by DB
                .ForMember(dest => dest.CreatedBy, opt => opt.Ignore()) // set in service
                .ForMember(dest => dest.Version, opt => opt.MapFrom(src => 1))
                .ForMember(dest => dest.IsActive, opt => opt.MapFrom(src => src.IsActive ?? true))
                .ForMember(dest => dest.UpdatedBy, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(_ => DateTime.UtcNow))
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore());

            // Map update request -> entity (only update non-null fields)
            CreateMap<UpdateDocumentTemplateRequest, DocumentTemplate>()
                .ForMember(dest => dest.Name, opt => opt.Condition(src => !string.IsNullOrEmpty(src.Name)))
                .ForMember(dest => dest.Content, opt => opt.Condition(src => !string.IsNullOrEmpty(src.Content)))
                .ForMember(dest => dest.TemplateType, opt => opt.Ignore())
                .ForMember(dest => dest.IsActive, opt => opt.Condition(src => src.IsActive.HasValue))
                .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(_ => DateTime.UtcNow))
                .ForAllMembers(opt => opt.Ignore());
        }
    }
}
